name: test
on:
   workflow_dispatch:
jobs:
    default:
        runs-on: ubuntu-latest
       
        steps:
        - name: install node
          run: sudo apt-get install nodejs
        - name: Checkout
          uses: actions/checkout@v3
        - name: node
          run: npm install
        - name: set 
          run: npm run aws:credentials:config:dev
        - name: ls
          run: aws ec2 describe-instances
