name: test
on:
   workflow_dispatch:
jobs:
    default:
        runs-on: ubuntu-latest
        container:
            image: node:18.0.0
        steps:
        - name: npm install
          run: npm install
        - name: set 
          run: aws:credentials:config:dev
        - name: ls
          run: aws ec2 describe-instances
