name: test
on:
   workflow_dispatch:
    inputs:
      job:
        description: 'iniciar qual job?'
        required: true
        type: choice
        options:
          - promote-to-production
          - promote-react
jobs:
    default:
        runs-on: ubuntu-latest
        if: inputs.job == 'promote-to-production'
        steps:
        - name: install node
          run: |
             echo "GITHUB_COMMIT=$(echo $GITHUB_SHA)" >> $GITHUB_ENV
             echo "GITHUB_BUILD_NUMBER=$(echo $GITHUB_RUN_NUMBER)" >> $GITHUB_ENV
        - name: Checkout
          uses: actions/checkout@v3
        - name: print
          run: echo "$GITHUB_COMMIT"
        - name: set 
          run: echo "$GITHUB_BUILD_NUMBER"
        - name: ls
          run: echo $GITHUB_SHA
    promote-react:
      runs-on: ubuntu-latest
      if: inputs.job == 'promote-to-production'
      steps:
      - name: test
        run: echo "Escolhi promote-react"

      