name: test
on:
   workflow_dispatch:
jobs:
    default:
        runs-on: ubuntu-latest
       
        steps:
        - name: install node
          run: |
             echo "GITHUB_COMMIT=$(echo $GITHUB_SHA)" >> $GITHUB_ENV
             echo "GITHUB_BUILD_NUMBER=$(echo $GITHUB_RUN_NUMBER)" >> $GITHUB_ENV
        - name: Checkout
          uses: actions/checkout@v3
        - name: print
          run: echo "$GITHUB_COMMIT"
        - name: set 
          run: echo "$GITHUB_BUILD_NUMBER"
        - name: ls
          run: aws ec2 describe-instances
