name: test-logica2
on:
  workflow_dispatch:
jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: test create tag
        uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: "test"
          tag_exists_error: false
          message: "Latest release"
 
