name: test-logica2
on:
  workflow_dispatch:
jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: tag
        run: |
          LAST_COMMIT_MESSAGE='teste'    
          git tag -a deploy-$GITHUB_BUILD_NUMBER -m "$LAST_COMMIT_MESSAGE"
          git push --tags --force

