name: test-logica2
on:
  workflow_dispatch:
jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: test create tag
        run: echo "${{vars.VARI_TESTE}}"
        id: "tag_create"
        
 
