name: test-logica
on:
  workflow_dispatch:
    inputs:
      ambiente:
        description: 'realizar deploy em qual ambiente?'
        required: true
        type: choice
        options:
          - deploy-to-staging
          - deploy-to-production
  push:

jobs:
     default:
        runs-on: ubuntu-latest
        if: github.ref != 'refs/heads/master'
        steps:
        - name: teste não estou na master
          run: echo "não estou na master" 
     master:
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/master'
        steps:
        - name: teste estou na master
          run: echo "estou na master" 
     stg:
      runs-on: ubuntu-latest
      if: inputs.ambiente == 'deploy-to-staging'
      steps:
      - name: stg
        run: echo "estou na stg" 
     prd:
      runs-on: ubuntu-latest
      if: inputs.ambiente == 'deploy-to-production'
      steps:
      - name: stg
        run: echo "estou na prd" 



    

