name: test-logica2
on:
  workflow_dispatch:
jobs:
     default:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v3
          - name: tag
            run: |
                USER_NAME=`git log -1 --pretty=%aN`
                USER_EMAIL=`git log -1 --pretty=%ae
                LAST_COMMIT_MESSAGE=`git log -1 --pretty=%B`    
                git tag -a deploy-$GITHUB_BUILD_NUMBER -m "$LAST_COMMIT_MESSAGE"
                git push --tags --force

