name: test-logica
on:
  workflow_dispatch:
    inputs:
      ambiente:
        description: 'realizar deploy em qual ambiente?'
        required: true
        type: choice
        options:
          - deploy-to-staging
          - deploy-to-production
  push:

jobs:
     default:
        runs-on: ubuntu-latest
        if: github.event_name == 'push'
        steps:
        - name: teste não estou na master
          run: echo "fiz push" 
     stg:
      runs-on: ubuntu-latest
      if: inputs.ambiente == 'deploy-to-staging'
      steps:
      - name: stg
        run: echo "manual" 
     prd:
      runs-on: ubuntu-latest
      if: inputs.ambiente == 'deploy-to-production'
      steps:
      - name: prd
        run: echo "manual"
      
